### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by aaronlidman** [osmlab/to-fix#7]
- [x] better JOSM bounds
  - [x] nodes: too small, use map bounds when it's a node
  - [x] ways: buffer a little, give some context
- [x] OSM tilelayer
- [x] Satellite (Bing & Mapbox) tilelayers
- [x] [Figure out datastore](https://github.com/osmlab/to-fix/issues/3)
- [x] User tracking
- [x] iD integration
  - iframe? fork (iD minus)? link?
- [ ] Automate source updates
  - is the implied tracking idea possible?
